services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  openapi-generator:
    image: openapitools/openapi-generator-cli:latest
    user: 1000:1000
    command: >
      generate 
      --git-user-id qushot
      --git-repo-id gin-todo-api
      -g go-gin-server
      --additional-properties=interfaceOnly=true
      -i /openapi.yaml
      -o /project/sample
    volumes:
      - .:/project
      - ./openapi.yaml:/openapi.yaml

  tbls:
    image: ghcr.io/k1low/tbls:latest
    user: 1000:1000
    working_dir: /work_tbls
    volumes:
      - .:/work_tbls
    depends_on:
      - postgres
    entrypoint: >
      tbls doc --rm-dist "postgres://postgres:pass@postgres:5432/postgres?sslmode=disable&search_path=public"

volumes:
  postgres_data:
