openapi: 3.0.0
info:
  title: Todo API
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/todos:
    get:
      summary: Todo の一覧を取得する
      tags:
        - Todo
      operationId: listTodos
      responses:
        '200':
          description: 正常に一覧を取得しました
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: 新しい Todo を作成する
      tags:
        - Todo
      operationId: createTodo
      requestBody:
        description: 作成する Todo の情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: Todo が正常に作成されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /api/v1/todos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: Todo の一意な識別子 (UUID)
        schema:
          type: string
          format: uuid
    get:
      summary: 指定した ID の Todo を取得する
      tags:
        - Todo
      operationId: getTodo
      responses:
        '200':
          description: 正常に取得しました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: 指定した ID の Todo を更新する
      tags:
        - Todo
      operationId: updateTodo
      requestBody:
        description: 更新する Todo の情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '200':
          description: Todo が正常に更新されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: 指定した ID の Todo を削除する
      tags:
        - Todo
      operationId: deleteTodo
      responses:
        '204':
          description: Todo が正常に削除されました
          content: {}
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        done:
          type: boolean
      required:
        - id
        - title
        - content
        - done
    NewTodo:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        done:
          type: boolean
      required:
        - title
        - content
        - done
