name: tbls
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "postgres/**/*.sql"

jobs:
  tbls:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: postgres
        volumes:
          - ./postgres/init:/docker-entrypoint-initdb.d
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: k1low/setup-tbls@v1
      - run: tbls doc --rm-dist
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'exec: tbls doc by github actions'
          git push
